# Webpack
webpack:
  # ビルド対象のdockerfileのパス
  build: ./webpack

  # マウントするボリューム
  volumes:
    - ./app:/my_webpack/app
    - ./webpack/package.json:/my_webpack/package.json
    - ./webpack/webpack.config.js:/my_webpack/webpack.config.js
